import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./styles/globals.css";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-color1">
				<Navbar />
				<main className="lg:w-[90%] mx-auto bg-color1 font-roboto">
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}
