import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./styles/globals.css";
export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="bg-black">
				<main className="lg:w-[90%] mx-auto bg-bg">
					<Navbar />
					{children}
					<Footer />
				</main>
			</body>
		</html>
	);
}
